<!--  Copyright (c) Files Community. Licensed under the MIT License.  -->
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
		<Platforms>x64</Platforms>
		<RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
		<IsPackable>false</IsPackable>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MSTest.TestAdapter" />
		<PackageReference Include="MSTest.TestFramework" />
		<PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Files.Shared\Files.Shared.csproj" />
	</ItemGroup>

</Project>
